patrickmohrmann/earthdawn4eV2

.eslintrc.json, earthdawn4e.css, earthdawn4e.mjs, lang/de.json, less/earthdawn4e.less, less/global/system-settings.less, module/settings.mjs, module/tours/earthdawn-settings.json, module/tours/spellcasting.json, module/tours/tours.mjs
First Tour,
Help, Bug and Changlog button in the setting menu
System configuration preparation with css
=> Patrick config

earthdawn4e.mjs, module/config.mjs, module/utils.mjs, templates/actor/character-details/details-general.hbs
Closes #325.
@patrickmohrmann I only changed the one lookup mentioned in the issue. If there is more to adjust, that should be done before merging.
=> Pre-Localize config #325

earthdawn4e.css, earthdawn4e.mjs, less/global/global.less, module/applications/global/roll-prompt.mjs, module/config.mjs, module/data/other/roll-options.mjs, templates/global/roll-prompt.hbs
=> Roll step from dice icon #137

earthdawn4e.css, less/global/global.less, less/item/item-sheet-global.less
real quick fix for an editor css issue
=> fixed editor issue

module/data/other/roll-options.mjs, module/dice/ed-roll.mjs, module/documents/actor.mjs, templates/global/roll-prompt.hbs
=> Closes #339 and Closes #392

earthdawn4e.css, lang/de.json, lang/en.json, less/chat/chat-messages.less, less/chat/roll-messages.less, less/earthdawn4e.less, module/applications/global/roll-prompt.mjs, module/config.mjs, module/data/other/roll-options.mjs, module/dice/ed-roll.mjs, module/documents/actor.mjs, module/hooks/chat.mjs, module/hooks/ready.mjs, module/utils.mjs, templates/dice/chat-flavor/action-roll-flavor.hbs, templates/dice/chat-flavor/arbitrary-roll-flavor.hbs, templates/dice/chat-flavor/damage-roll-flavor.hbs, templates/dice/chat-flavor/effect-roll-flavor.hbs, templates/dice/dice-partials/roll-step-modifier.hbs, templates/dice/dice-partials/roll-successes.hbs, templates/dice/dice-partials/roll-target-modifier.hbs, templates/dice/tooltip.hbs
Create base for Roll messages rendering.
=> Closes #245

earthdawn4e.css, less/earthdawn4e.less, less/global/global.less, less/item/class.less, module/applications/item/item-sheet.mjs, module/config.mjs, module/data/_module.mjs, module/data/advancement/_module.mjs, module/data/advancement/advancement-level.mjs, module/data/advancement/base-advancement.mjs, module/data/fields.mjs, module/data/item/templates/class.mjs, module/documents/item.mjs, module/hooks/init.mjs, module/utils.mjs, templates/item/item-partials/item-details/other-tabs/discipline-advancement.hbs, templates/item/item-partials/main-section.hbs, templates/item/item-partials/navigator-section.hbs
Implement basic functionality and layout for advancement models in class items.
Should later be styled according to the class type (e.g., correct name for ressource step, karma/devotion, etc).
=> Implements #267

earthdawn4e.css, less/earthdawn4e.less, less/prompts/legend-points-history.less, less/prompts/roll-prompt.less, module/applications/actor/base-sheet.mjs, module/applications/global/_module.mjs, module/applications/global/legend-point-history-earned-prompt.mjs, module/config.mjs, module/data/actor/pc.mjs, module/data/advancement/_module.mjs, module/data/advancement/lp-earning-transaction.mjs, module/data/advancement/lp-spending-transaction.mjs, module/data/advancement/lp-tracking.mjs, module/data/advancement/lp-transaction.mjs, module/data/fields.mjs, module/documents/actor.mjs, module/utils.mjs, templates/actor/character-details/details-legend.hbs, templates/actor/legend-points/history-earned.hbs
=> Data Models for LP Tracking

.gitignore, earthdawn4e.css, lang/de.json, less/global/system-settings.less, module/settings.mjs
I explicitly left the dual choice setting for the chat potrait. that way it is just nicer to handle
=> 601 refactor dual choice strings settings to checkboxes

templates/item/item-partials/item-details/other-tabs/discipline-advancement.hbs
intermediate solution. a further issue is created as feature to add bin icons on each uuid
closes #502
=> remove items from Pool - hint next to bin icon

earthdawn4e.css, less/actor/character/character-sheet.less, less/global/global.less, module/data/actor/pc.mjs, templates/actor/character-details/details-legend.hbs, templates/item/item-partials/item-details/details/item-details-path.hbs
bloodmagic checked for equipped status but paths do not have that status.
=> fixing Bloodmagic damage from Path items

module/data/item/namegiver.mjs, templates/item/item-partials/item-details/details/item-details-namegiver.hbs
=> added tail attack option to namegiver item details

earthdawn4e.css, lang/de.json, lang/en.json, module/applications/global/roll-prompt.mjs, module/config.mjs, module/data/other/roll-options.mjs, module/dice/ed-roll.mjs, module/documents/actor.mjs, module/enrichers.mjs, module/hooks/ready.mjs, templates/dice/chat-flavor/action-roll-flavor.hbs, templates/dice/chat-flavor/arbitrary-roll-flavor.hbs, templates/dice/chat-flavor/damage-roll-flavor.hbs, templates/dice/chat-flavor/effect-roll-flavor.hbs, templates/global/roll-prompt.hbs
Fixes #637.
Additionally, some bugs had to be fixed in the actor document. Otherwise a roll could not be handled correctly.
=> Refactor Roll using rollType and bug fixes

module/dice/ed-roll.mjs
=> Set minimum roll result to 1

module/documents/item.mjs
=> Fix advancement ability pools not persisting items

module/data/actor/pc.mjs
=> Enable special abilities in char gen

module/applications/actor/base-sheet.mjs, module/applications/global/document-creation.mjs, module/applications/item/item-sheet.mjs, module/data/fields.mjs, module/data/other/roll-options.mjs, module/dice/ed-roll.mjs, module/documents/actor.mjs, module/hooks/chat.mjs
BREAKING! Only merge if Foundry V12 is the new base requirement for development.
=> Fix warnings and errors coming through Foundry V12

module/data/actor/pc.mjs, module/data/other/character-generation.mjs, templates/actor/generation/namegiver-selection.hbs
Closes #600 and fixes bugs in connection with this. 
Needs to be updated for V12, as done in #675.
=> Closes #600

system.json
Closes #679 - Update grid property in system.json
=> Closes #679 - Update grid property in system.json

lang/de.json, module/config.mjs, module/hooks/i18n.mjs, module/hooks/init.mjs, module/settings.mjs
=> Closes #350

module/applications/item/item-sheet.mjs, module/data/advancement/advancement-level.mjs, module/data/advancement/base-advancement.mjs, module/data/advancement/lp-spending-transaction.mjs, module/data/fields.mjs, module/data/item/templates/ability.mjs, module/data/item/templates/knack-item.mjs, module/data/other/character-generation.mjs, module/handlebar-helpers.mjs, templates/item/item-partials/item-details/other-tabs/discipline-advancement.hbs
Closes #493. This includes further adaptations and edits as a consequence of changing these fields.
=> Closes #493

module/applications/actor/character-generation-prompt.mjs, module/config.mjs, module/data/actor/pc.mjs, module/data/actor/templates/namegiver.mjs, module/data/item/talent.mjs, module/data/item/templates/sorcery-item.mjs, module/data/other/character-generation.mjs, module/handlebar-helpers.mjs, module/settings.mjs, module/utils.mjs, templates/actor/generation/spell-selection.hbs, templates/item/item-partials/item-details/descriptions/item-description-spell.hbs, templates/item/item-partials/item-details/details/item-details-talent.hbs
Closes #100.
Currently has a table style hardcoded in the template for debugging visuals. Needs to be reworked.
=> Spell selection in character generation

lang/de.json, lang/en.json, module/config.mjs, module/data/_module.mjs, module/data/abstract.mjs, module/data/fields.mjs, module/data/item/templates/item-description.mjs, module/documents/actor.mjs, module/settings.mjs, module/utils.mjs, templates/item/item-partials/item-details.hbs
=> Implement eartdawn id Closes #719

earthdawn4e.css, lang/de.json, lang/en.json, less/sheets/owned-items-view.less, module/applications/actor/base-sheet.mjs, module/handlebar-helpers.mjs, module/settings.mjs, templates/actor/cards/equipment-card.hbs, templates/actor/character-details/details-talents.hbs
=> 663 talent devider system setting

templates/global/document-creation.hbs
=> Closes #674

module/applications/actor/character-generation-prompt.mjs, module/data/other/character-generation.mjs, templates/actor/generation/class-selection.hbs
=> Closes #677

lang/de.json, lang/en.json, module/data/item/armor.mjs, module/data/item/namegiver.mjs, module/data/item/shield.mjs, module/documents/actor.mjs, module/settings.mjs, templates/item/item-partials/item-details/descriptions/item-description-armor.hbs, templates/item/item-partials/item-details/descriptions/item-description-shield.hbs, templates/item/item-partials/item-details/details/item-details-namegiver.hbs
resolves #979  and replaces #994
=> Living armor2

lang/de.json, lang/en.json, module/config.mjs, module/data/item/devotion.mjs, module/data/item/skill.mjs, module/data/item/talent.mjs, module/data/item/templates/ability.mjs, module/data/item/templates/action.mjs, module/utils.mjs, templates/item/item-partials/item-details.hbs, templates/item/item-partials/item-details/descriptions/item-description-devotion.hbs, templates/item/item-partials/item-details/descriptions/item-description-skill.hbs, templates/item/item-partials/item-details/descriptions/item-description-talent.hbs, templates/item/item-partials/item-details/details/item-details-abilities.hbs, templates/item/item-partials/item-details/details/item-details-talent.hbs, templates/item/item-partials/item-details/partials/abilities.hbs
=> replaced html code with formfields for abilities

module/data/item/templates/physical-item.mjs, module/documents/item.mjs, templates/item/item-partials/item-details/partials/tailor-to-namegiver.hbs
=> refactored weight dataModel

module/hooks/ready.mjs, module/hooks/sidebar.mjs
addded to the sidebar hook
resolves #1029
=> solved dice symbol issue

lang/de.json, lang/en.json, templates/item/item-partials/item-details/other-tabs/discipline-advancement.hbs
=> Fix advancement levels

module/data/abstract.mjs, module/utils.mjs
=> Handle onDrop methods gracefully

module/data/item/templates/ability.mjs, templates/actor/cards/ability-card.hbs
=> display final Rank on ability card

lang/de.json, module/data/item/namegiver.mjs, templates/item/item-partials/item-details/descriptions/item-description-namegiver.hbs
=> provides ability and effects links inside an namegiver item

module/data/actor/pc.mjs, module/data/item/discipline.mjs, module/documents/actor.mjs
=> 344 advancement method 1   standard

module/data/item/templates/class.mjs, module/documents/actor.mjs
=> Update karma and devotion resource on level up

module/data/abstract.mjs
=> harmonized application class 

lang/de.json, module/data/item/discipline.mjs, module/data/item/templates/class.mjs, templates/advancement/advancement-requirements.hbs, templates/advancement/class-advancement-summary.hbs
=> Circle information missing in update prompt

lang/de.json, module/applications/actor/character-generation-prompt.mjs, module/data/other/character-generation.mjs, templates/actor/generation/attribute-assignment.hbs, templates/actor/generation/class-selection.hbs, templates/actor/generation/equipment.hbs, templates/actor/generation/language-selection.hbs, templates/actor/generation/namegiver-selection.hbs, templates/actor/generation/skill-selection.hbs, templates/actor/generation/spell-selection.hbs
=> solved smaller issues in char gen

lang/de.json, module/applications/actor/character-generation-prompt.mjs, templates/actor/generation/attribute-assignment.hbs, templates/actor/generation/class-selection.hbs, templates/actor/generation/equipment.hbs, templates/actor/generation/skill-selection.hbs, templates/actor/generation/spell-selection.hbs
=> finished char gen localizations

lang/de.json, module/applications/actor/character-generation-prompt.mjs, module/data/other/character-generation.mjs, templates/actor/generation/class-selection.hbs
=> adding talents from the namegiver to the char gen

lang/de.json, module/documents/actor.mjs, module/settings.mjs
Tail attack looks for ability with edid for unarmed combat now first.
=> Fix tail attack not using unarmed combat

module/applications/item/item-sheet.mjs, module/applications/item/physical-item-sheet.mjs, module/data/thread/thread-base.mjs, templates/item/item-partials/item-details/other-tabs/threads.hbs
=> show and hide thread data

module/applications/actor/base-sheet.mjs, module/data/item/templates/ability.mjs, module/data/roll/ability.mjs
resolved #1233
resolved #1234
added getDifficulty to target parameter in attackroll
=> roll fixes

earthdawn4e.css, lang/de.json, less/sheets/actor-sheet-layout.less, module/applications/actor/base-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/applications/global/prompt-factory.mjs, module/data/actor/templates/sentient.mjs, templates/actor/actor-partials/actor-section-top.hbs, templates/actor/actor-tabs/configuration.hbs, templates/actor/cards/attributes-none-pc-card.hbs, templates/actor/cards/damage-none-character-card.hbs, templates/actor/cards/health-none-character-card.hbs
=> NPC actor APPV2

lang/de.json, module/config.mjs, module/data/item/templates/ability.mjs, module/data/item/templates/action.mjs, module/data/item/templates/physical-item.mjs, module/data/item/templates/targeting.mjs, module/data/item/weapon.mjs, module/data/roll/damage.mjs
=> removed none as option from config entries

module/applications/actor/_module.mjs, module/applications/actor/character-sheet.mjs, module/applications/actor/common-sheet.mjs, module/applications/actor/group-sheet.mjs, module/applications/actor/namegiver-sheet.mjs, module/applications/actor/npc-sheet.mjs, module/applications/actor/sentient-sheet.mjs, module/hooks/init.mjs, module/utils.mjs, templates/actor/actor-tabs/description.hbs
I'm starting to refactor the actor applications to have them similar to our data Models. this allows us better to differentiate between options certain actor types do not have and others do.
resolves #1312
=> introduced Group actor and refactored sheets

lang/de.json, lang/en.json, module/config.mjs, module/data/_module.mjs, module/data/abstract.mjs, module/data/effects/_module.mjs, module/data/effects/eae-change-data.mjs, module/data/effects/eae-duration.mjs, module/data/effects/eae.mjs, module/documents/_module.mjs, module/documents/active-effect.mjs, module/documents/item.mjs, module/hooks/init.mjs, template.json
Ccreate basic document and data models for earthdawn active effects
=> 521-eae---datamodel

module/applications/actor/common-sheet.mjs
Only need to extend correct superclass
This adds basic drag and drop handlers
=> Drag-Drop Actor Sheets

module/applications/actor/base-sheet.mjs, module/data/chat/damage.mjs, module/documents/actor.mjs
Streamlining and linting
This is a suggestion on what how I meant it. It's just minor cleanup. If you think that's fine you can merge it. If not, you can just deny the PR.
=> Suggestion from Chris' comments

lang/de.json, module/applications/_module.mjs, module/applications/actor/common-sheet.mjs, module/applications/effect/_module.mjs, module/applications/effect/eae-sheet.mjs, module/applications/item/item-sheet.mjs, module/config.mjs, module/data/effects/eae-change-data.mjs, module/data/effects/eae-duration.mjs, module/data/effects/eae.mjs, module/data/fields/formula-field.mjs, module/documents/active-effect.mjs, module/documents/item.mjs, module/handlebar-helpers.mjs, module/hooks/init.mjs, templates/actor/actor-partials/actor-section-buttons.hbs, templates/actor/actor-tabs/specials.hbs, templates/actor/cards/attribute-card.hbs, templates/actor/cards/attributes-none-pc-card.hbs, templates/effect/changes.hbs, templates/effect/details.hbs, templates/effect/duration.hbs, templates/form/group/general.hbs, templates/form/input/base-metric.hbs, templates/global/card-options-effect.hbs, templates/global/effect-card.hbs, templates/item/item-partials/item-details/item-effects.hbs
Closes #1074
- Hooks and Macros will be added later when they have functionality
- Formula Value have a tooltip with a preview of their final value if possible
- Miro has the possible application targets
- Target Abilities are only shown on Item Effects since Actor Effects don't have targets in the sense of TargetingTemplate
=> 1074-eae---sheet-design

module/data/item/spell.mjs
This is needed for Foundry Dev2 Build 335
due to https://github.com/foundryvtt/foundryvtt/issues/11973
=> Fix spell joint validation

module/data/item/devotion.mjs, module/data/item/questor.mjs, module/data/item/templates/class.mjs, templates/actor/actor-tabs/legend.hbs, templates/advancement/class-advancement-option-choice.hbs, templates/advancement/class-advancement-spell-selection.hbs
=> 1086-chris-show-optional-devotions-on-questor-upgrade

lang/de.json, module/applications/effect/eae-sheet.mjs, module/data/effects/eae.mjs, module/settings.mjs, templates/effect/changes.hbs
EdIdField seems to have some problem with initializing its defaults. The field here should be initialized with an empty string so it makes more sense for users to click into the input field.
This can be fixed later, it doesn't have implications for the functionality.
=> Add ability as an edid field that can be searched for default edids from settings

lang/de.json, module/data/fields/edid-field.mjs, module/utils.mjs
- fix cleaning
- fix initialization
- use Foundry's core `slugify` function
- add form input rendering
=> Improve EdId Fields

module/documents/item.mjs, templates/effect/details.hbs
=> 287-eae---effect-bonus-function

module/applications/global/prompt-factory.mjs, module/config.mjs, module/documents/actor.mjs, module/settings.mjs
=> removed ed ids for know down and jump up and replaced it with actions

lang/de.json, module/data/abstract.mjs, module/data/effects/eae.mjs
Will be filled and used in later stories
=> Add source information for active effects

module/data/actor/templates/movement.mjs
=> make movement data model nullable

module/data/chat/attack.mjs, module/data/item/templates/targeting.mjs
=> fixed trigger reaction story

documentation/Functional Specification/character-generation.md, module/settings.mjs
=> 1452 fs documentation character generation

eslint.config.mjs, module/applications/effect/eae-sheet.mjs, module/data/actor/pc.mjs, module/data/effects/eae-change-data.mjs
- fix not being able to delete changes from effect
- set default change mode to ADD
- fix durabilityBonus application and calculation
=> smaller-active-effect-fixes

earthdawn4e.css, lang/de.json, less/global/global.less, less/item/item-sheet-global.less, less/sheets/item-sheet-layout.less, less/sheets/owned-items-view.less, module/applications/item/class-item-sheet.mjs, module/applications/item/item-sheet.mjs, module/applications/item/physical-item-sheet.mjs, module/data/item/templates/item-description.mjs, module/utils.mjs, templates/actor/actor-tabs/talents.hbs, templates/actor/cards/knack-ability-card.hbs, templates/actor/cards/knack-karma-card.hbs, templates/actor/cards/knack-maneuver-card.hbs, templates/global/editor-brief.hbs, templates/item/item-partials/item-section-top.hbs
in short, this is what this pr is about. I added all kinds of knack visualizations
resolves #444
=> 444 show karma and maneuver knacks

module/data/chat/base-message.mjs, module/data/chat/damage.mjs, module/documents/chat.mjs, module/hooks/chat.mjs
See this issue for more info: https://github.com/foundryvtt/foundryvtt/issues/11984
We are currently only editing the core HTML, so can do it via hook. In the future we might wanna think about implementing our own rendering methods, if the messages get more complex/complicated.
Maybe put this one the feature track @patrickmohrmann ?
=> Fix new chat message rendering workflow

module/data/actor/pc.mjs
=> Return 0 if no durability items available

module/data/roll/common.mjs, templates/prompts/roll-prompt.hbs
Fix #1479
The step is not displayed correctly in the formula of the chat message yet. This needs a deep dive, I couldn't find where the problem is yet. In order to not block this issue, merge like this. The original bug is fixed.
Maybe create a new bug for the wrong formula in the chat message @patrickmohrmann ?
=> 1479-bug-manual-difficulty-overwrite-in-roll-prompt-not-working

lang/en.json, templates/item/item-partials/item-details/details/item-details-spell.hbs
Additions to localise EN code. Alteration to .hbs that had inaccurate localise code in it.
=> Add to EN Localise

earthdawn4e.css, less/sheets/owned-items-view.less, templates/actor/actor-tabs/powers.hbs, templates/actor/cards/maneuver-card.hbs, templates/actor/cards/power-card.hbs
=> 1493 powers clean up minor changes

module/applications/global/prompt-factory.mjs
=> recover from stun only if stun damage is >0

module/applications/actor/character-generation-prompt.mjs, module/applications/global/document-creation.mjs, module/data/actor/pc.mjs
resolves #1501 reset talent points on class change
resolves #975  add spend optional points back to available points after changing an optional talent
resolves #1048 create character without char gen
=> 1501 bug talent ranks are not reset on changing class

templates/actor/character-sheet.hbs, templates/actor/npc-sheet.hbs, templates/prompts/assign-legend.hbs, templates/prompts/roll-prompt.hbs, templates/standard-sheet.hbs
I did a search for all instances of the vasgothia header and footer and I believe that I've removed them all.
=> Removed Vasgothia Header/Footer

module/data/item/power.mjs, module/utils.mjs, templates/actor/actor-tabs/powers.hbs, templates/actor/cards/power-card.hbs, templates/item/item-partials/item-details/details/item-details-abilities.hbs, templates/item/item-partials/item-details/details/item-details-power.hbs, templates/item/item-partials/item-details/partials/roll-type.hbs
resolves #1360 
resolves #1361
=> 1360 roll powers

module/data/actor/templates/sentient.mjs
Bases on health ratings and only if the ratings are > 0.
=> Automatically add dead/unconscious status effect

module/documents/_module.mjs, module/documents/combat.mjs, module/documents/combatant.mjs, module/hooks/init.mjs
This will be needed for ActiveEffects, initiative abilities, measure templates, and so on
=> Add custom Combat and Combatant document classes

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/applications/actor/common-sheet.mjs, module/settings.mjs
=> Enhance delete functionality to support direct deletion with Shift key

earthdawn4e.css, less/sheets/actor-sheet-layout.less, module/data/actor/_module.mjs, module/data/actor/creature.mjs, module/data/actor/dragon.mjs, module/data/actor/horror.mjs, module/data/actor/npc.mjs, module/data/actor/spirit.mjs, module/data/actor/templates/none-character.mjs, module/data/actor/templates/sentient.mjs, module/utils.mjs, templates/actor/actor-tabs/equipment.hbs, templates/actor/actor-tabs/general.hbs, templates/actor/cards/special-abilities-characters.hbs, templates/actor/cards/special-abilities-npc.hbs
resolves #1495 
finished up the creature sheet by removing all none creature related options
=> 1495 smaller changes to current sheet to fulfill creature needs

earthdawn4e.css, less/global/config.less, less/global/global.less
Very small changes to global.less and config.less.
This sets up some basic variables and also removes the window header block allowing the background to cover the window.
No other changes have been made bar some neatening up.
=> Basic Global .less Changes

documentation/User Functions/UF_ActorSheetEdNamegiver/UF_ActorSheetEdNamegiver-onDropItem.md, lang/de.json, module/applications/actor/namegiver-sheet.mjs, module/data/item/namegiver.mjs
=> include singleton check for items on drop

module/applications/effect/eae-sheet.mjs
=> fix eae edit mode error

module/documents/_module.mjs, module/documents/actor.mjs, module/documents/item.mjs, module/documents/migration/_module.mjs, module/documents/migration/actor/_module.mjs, module/documents/migration/actor/old-system/_module.mjs, module/documents/migration/actor/old-system/character.mjs, module/documents/migration/actor/old-system/none-character.mjs, module/documents/migration/item/_module.mjs, module/documents/migration/item/old-system/_module.mjs, module/documents/migration/item/old-system/armor.mjs, module/documents/migration/item/old-system/devotion.mjs, module/documents/migration/item/old-system/discipline.mjs, module/documents/migration/item/old-system/equipment.mjs, module/documents/migration/item/old-system/knack.mjs, module/documents/migration/item/old-system/mask.mjs, module/documents/migration/item/old-system/matrix.mjs, module/documents/migration/item/old-system/namegiver.mjs, module/documents/migration/item/old-system/power.mjs, module/documents/migration/item/old-system/shield.mjs, module/documents/migration/item/old-system/skill.mjs, module/documents/migration/item/old-system/spell.mjs, module/documents/migration/item/old-system/talent.mjs, module/documents/migration/item/old-system/weapon.mjs
First migration PR, as agreed only the document migration to differentiate the old to the new item types
=> Migration data model basics

module/applications/advancement/class-advancement.mjs, module/data/item/talent.mjs, module/data/item/templates/ability.mjs, module/data/item/templates/class.mjs
=> made talent learn options optional for class increase

module/documents/actor.mjs
=> fixed equipment roll

module/data/item/power.mjs, module/settings.mjs, templates/actor/actor-tabs/powers.hbs
resolve #1580
this will be handled via rolltype
=> remove isCreatureAttack ed-id

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/config/legend.mjs, module/data/actor/pc.mjs, module/data/item/devotion.mjs, module/data/item/discipline.mjs, module/data/item/path.mjs, module/data/item/questor.mjs, module/data/item/skill.mjs
=> 1106 update rules for lp tracking

module/config/system.mjs, module/data/fields/edid-field.mjs, module/settings.mjs, module/utils.mjs
=> create edid config

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json
only german lang file, 
p.s. please ignore the second german push
=> Lang cleanup 2

earthdawn4e.css, less/global/global.less, less/sheets/actor-sheet-layout.less, templates/actor/cards/attribute-card.hbs
Dots have been added under INC on the attributes, they are empty until LP is spent then they fill.
A few other small cosmetic changes have been made, these are padding/margins that correct some imperceptable issues that were messy
=> LP Increase Dots

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/hooks/init.mjs
=> Clean up lang 4

dictionaries/ed4e-words.txt, earthdawn4e.css, less/sheets/actor-sheet-layout.less, less/sheets/item-sheet-layout.less, module/config/migrations.mjs, module/data/item/migration/_module.mjs, module/data/item/migration/old-system-V082/_module.mjs, module/data/item/migration/old-system-V082/action.mjs, module/data/item/migration/old-system-V082/attribute.mjs, module/data/item/migration/old-system-V082/description.mjs, module/data/item/migration/old-system-V082/difficulty.mjs, module/data/item/migration/old-system-V082/level.mjs, module/data/item/migration/old-system-V082/tier.mjs, module/data/item/skill.mjs, module/data/item/talent.mjs, module/documents/migration/item/old-system-V082/abilities.mjs, module/documents/migration/item/old-system-V082/defenses.mjs, module/documents/migration/item/old-system-V082/image.mjs, module/documents/migration/item/old-system-V082/roll-type-Migration.mjs, module/documents/migration/item/old-system-V082/skill.mjs, module/documents/migration/item/old-system-V082/talent.mjs
=> Skill migration 2

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/hooks/ready.mjs, module/settings.mjs, templates/system-messages/update-message-v1_0_0.hbs
=> Create introduction message for system update

module/config/migrations.mjs, module/data/item/devotion.mjs, module/data/item/migration/old-system-V082/attribute.mjs, module/data/item/migration/old-system-V082/difficulty.mjs, module/documents/migration/item/old-system-V082/devotion.mjs
=> migrate devotions

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/applications/hud/token-hud.mjs, module/data/item/templates/class.mjs, templates/combat/combatant-config.hbs, templates/global/document-creation.hbs
might be the last one for now... fingers crossed
=> Lang clean up 5002

.github/workflows/find-unused-localizations.yml, tools/find-unused-lang-keys.mjs, tools/localization-checker/_module.mjs, tools/localization-checker/base.mjs, tools/localization-checker/cli-config.mjs, tools/localization-checker/missing-keys.mjs, tools/localization-checker/unused-keys.mjs
Closes #1724
This PR refactors the localization checker into discrete, reusable modules for improved maintainability and clarity. The monolithic localization checker has been split into specialized modules with clear responsibilities and enhanced GitHub Actions integration.
- **Modularized Architecture**: Split the main localization checker into separate modules:
- - Handles detection of unused localization keys `UnusedLocalizationChecker`
- - Handles detection of missing localization keys `MissingLocalizationChecker`
- Supporting CLI configuration modules
- **Enhanced GitHub Actions Integration**:
- Improved workflow compatibility with existing GitHub Actions workflows
- Better integration with and workflows `check-missing-localizations.yml``find-unused-localizations.yml`
- Enhanced …
=> Modularize Localization Checking Tools

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/data/combatant/combatant.mjs, templates/effect/duration.hbs
=> More last lang clean ups 200

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/data/item/mask.mjs, templates/item/item-partials/item-details.hbs, templates/item/item-partials/item-details/descriptions/item-description-discipline.hbs, templates/item/item-partials/item-details/descriptions/item-description-knackAbility.hbs, templates/item/item-partials/item-details/descriptions/item-description-knackKarma.hbs, templates/item/item-partials/item-details/descriptions/item-description-knackManeuver.hbs, templates/item/item-partials/item-details/descriptions/item-description-namegiver.hbs, templates/item/item-partials/item-details/descriptions/item-description-path.hbs, templates/item/item-partials/item-details/descriptions/item-description-shipWeapon.hbs, templates/item/item-partials/item-details/details/item-details-knackAbility.hbs, templates/item/item-partials/item-details/details/item-details-knackKarma.hbs, templates/item/item-partials/item-details/details/item-details-knackManeuver.hbs, templates/item/item-partials/item-details/details/item-details-talent.hbs, templates/item/item-partials/item-details/partials/matrix.hbs
item lang file support 
data/item done
=> Item lang clean up now better 40000

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/applications/advancement/learn-spell.mjs, module/applications/effect/eae-sheet.mjs, module/config/effects.mjs
Fixes the last detected keys from the localization check github workflow.
=> Update German localization for keys detected in github workflow

module/applications/actor/character-generation-prompt.mjs, templates/actor/generation/attribute-assignment.hbs, templates/actor/generation/class-selection.hbs, templates/actor/generation/language-selection.hbs, templates/actor/generation/namegiver-selection.hbs, templates/actor/generation/skill-selection.hbs
resolves #1197
removed context.object and replaced it with dedicated names
=> refactor character generation

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/data/item/discipline.mjs
=> Some smaller fixes

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/applications/item/class-item-sheet.mjs, module/config/items.mjs, templates/item/item-partials/item-details/other-tabs/discipline-advancement.hbs
=> Rename pool options2

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/data/item/discipline.mjs, module/data/item/questor.mjs
=> 1775 refactoring remove limitation for the first discipline to be only from char gen

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/applications/advancement/class-advancement.mjs, module/data/item/discipline.mjs, module/data/item/templates/class.mjs, templates/actor/legend-points/learn-spell.hbs, templates/advancement/class-advancement-spell-selection.hbs
resolves #1520 
learn spell option now appears during level up.
all spells are now grouped by circle in the choice list.
selecting spells is not actually possible
=> 1520 bug make spells during circle up selectable and limit them to the next level

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/applications/advancement/assign-legend.mjs
=> 1682 refactoring warn instead of error in lp assign

templates/actor/actor-tabs/general.hbs
resolves #1814 
resolves #1768
=> enable manual overwrite to current recovery tests

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/applications/global/prompt-factory.mjs, module/data/item/talent.mjs
versatility talents now have a limitation as written in the rules
=> Versatility talent limit validation

module/documents/actor.mjs, module/documents/item.mjs
migration has to be protected from updateEmbeddedDocuments, which does Partial updates.
resolves #2279
=> fix partial migration

documentation/wiki documentation/german/character-generation.html
It's easier if I just make my suggestions for your PR (#1834) like this instead of writing too many tiny comments....
=> 📝 Char Gen Docu Suggestion Chris

module/applications/actor/character-sheet.mjs, module/applications/actor/namegiver-sheet.mjs, module/applications/actor/sentient-sheet.mjs, module/data/chat/damage.mjs, module/documents/actor.mjs, module/services/roll-processor.mjs
Only refactoring, no functional changes.
=> 🎨 Clean up ed actor document class

module/data/abstract/system-data-model.mjs, module/data/item/knack-ability.mjs, module/data/roll/damage.mjs
=> 🐛 Ensure proper cancellation of operations in lifecycle events

module/documents/combat.mjs
=> 🐛 Reverse player character priority on initiative tie

module/workflows/workflow/rollable.mjs
=> 🎨 Add roll options step in rollable workflow

documentation/wiki documentation/german/character-generation.html
create an html page in code to enable referencing it in the wiki, journals etc.
=> Create char gen docu

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/data/chat/damage.mjs, module/data/roll/damage.mjs, module/documents/actor.mjs, module/workflows/workflow/raw-casting-workflow.mjs
=> ✨ Option to only consider natural armor on taking damage

lang/en.json
Complete update of the Character Sheet that all obvious placeholders are replaced, this also includes detailed Hints for all conditions
=> character-sheet-lang

module/documents/actor.mjs
Fix critical bug, missing import for prototype token config.
=> 🚑️ fix: update prototypeToken reference to use TOKEN from config module

earthdawn4e.css, less/global/config.less, less/global/global.less, less/global/variables.less, less/sheets/actor-sheet-layout.less
Parchment background working again
Rails behind h3 fixed to be readable on light-mode, this is an overall improvement to dark mode too.
=> fix-light-mode

lang/de.json, module/data/actor/pc.mjs, templates/actor/actor-tabs/general.hbs
refactors the intitiativePenalty calculation out of the initiative calculation to draw on this value for sheet display issues
=> fix initiative penalty calculation

dictionaries/0_8_2_migration-words.txt, module/services/migrations/v082/document-type-migrations/actor/_module.mjs, module/services/migrations/v082/document-type-migrations/actor/none-character.mjs, module/services/migrations/v082/document-type-migrations/item/namegiver.mjs, templates/actor/cards/attributes-none-pc-card.hbs
resolves #1741 
resolves #1740
=> 1740 migrate npcs

module/services/migrations/v082/document-type-migrations/item/talent.mjs
=> fix case of missing talentCategory

dictionaries/0_8_2_migration-words.txt, module/services/migrations/v082/document-type-migrations/item/power.mjs, module/services/migrations/v082/type-transformations.mjs
=> 1734 migrate powers maneuver

module/applications/advancement/assign-legend.mjs
=> fix none selectable actors

earthdawn4e.css, less/earthdawn4e.less, less/sheets/spell-card.less, less/sheets/spell-knack-card.less, module/applications/actor/sentient-sheet.mjs, module/data/item/spell-knacks.mjs, module/documents/actor.mjs, module/utils.mjs, templates/actor/actor-tabs/spells.hbs, templates/actor/cards/spell-card.hbs, templates/actor/cards/spell-knack-card.hbs
Closes #2307.
This is just playing around, all design can be changed.
There is no way to add knacks to the actor via UI yet. You have to add them programmatically via `createEmbeddedDocuments` on the actor.
=> Spell Knacks on Actor Sheets

templates/actor/actor-tabs/talents.hbs
tint fix to the npc talent header
=> npc=talent-header

module/services/migrations/v082/README.md, module/services/migrations/v082/document-migrations.mjs, module/services/migrations/v082/document-type-migrations/item/_module.mjs, module/services/migrations/v082/document-type-migrations/item/class.mjs
resolves #1730 
resolves #1731
=> fix path and questor basic migration

module/applications/actor/character-generation-prompt.mjs
without the tier the skills are not found in the collection
resolves #1882
=> add tier to language skills

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/data/item/templates/increasable-ability.mjs
=> add notification

module/documents/actor.mjs, module/workflows/workflow/attack-workflow.mjs
resolves #2331 
resolves #2337 
i know we should do a refactoring for those actions, and yes we will, its already assigned to #1628 
but the refactoring should not hold us back from doing the beta release.
=> 2331 bug unarmed combat button not working

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/applications/actor/character-sheet.mjs, module/applications/actor/sentient-sheet.mjs, module/applications/global/prompt-factory.mjs, module/config/rolls.mjs, module/data/actor/pc.mjs, module/data/actor/templates/sentient.mjs, module/data/item/mask.mjs, module/data/item/templates/rollable.mjs, module/data/roll/_module.mjs, module/data/roll/knockdown.mjs, module/documents/actor.mjs, module/services/migrations/v082/document-type-migrations/item/roll-type-Migration.mjs, module/services/roll-processor.mjs, module/workflows/workflow/_module.mjs, module/workflows/workflow/knockdown-workflow.mjs, templates/actor/actor-partials/actor-section-buttons-sentient.hbs, templates/actor/actor-tabs/general.hbs, templates/actor/prompts/knock-down-prompt.hbs, templates/chat/chat-flavor/knockdown-roll-flavor.hbs
resolves #1536 
resolves #1767 
resolves #1836
=> Refactor Knockdown test into workflow

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/data/item/devotion.mjs, module/data/item/skill.mjs, module/data/item/talent.mjs, module/data/item/templates/knack-item.mjs
=> make increase prompt more user friendly

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json, module/applications/item/_module.mjs, module/applications/item/mask-item-sheet.mjs, module/data/actor/templates/sentient.mjs, module/data/item/mask.mjs, module/hooks/init.mjs, module/utils.mjs, templates/item/item-partials/item-details/descriptions/item-description-mask.hbs
resolves #2089 
resolves #2311 
this is the basic creation of the Mask item with all the required data fields, and an option to have multiple powers / maneuvers on a  mask item. 
no drop on actor function included
=> 2311 mask datamodel

lang/de.json, lang/en.json, lang/fr.json, lang/pl.json
=> Fixes from earlier branch rebase

documentation/wiki documentation/german/character-gameplay.html, documentation/wiki documentation/german/characterbogen.html
suggestions to active PR #2373
=> add suggestions
