patrickmohrmann/earthdawn4eV2

module/data/item/templates/ability.mjs
module/handlebar-helpers.mjs
templates/item/item-partials/item-details/descriptions/item-description-talent.hbs

Closes #618.
The "attribute" field will be an empty string if no attribute is selected. This will also be the default value for abilities.

Add ability to select no attribute on abilities

---

module/data/_module.mjs
module/data/chat/_module.mjs
module/data/chat/attack.mjs
module/data/chat/base-message.mjs
module/documents/_module.mjs
module/documents/chat.mjs
module/hooks/init.mjs
template.json

Create the foundation for ED system specific ChatMessages documents and their DataModels. This currently has no additional functionality but serves as the basis for future enhancements (e.g. Chat Workflows for attacks, etc). The AttackMessage is just an example of how it might work.

Base for system specific ChatMessage Data and Documents

---

lang/de.json
lang/en.json
module/applications/actor/base-sheet.mjs
module/config.mjs
module/data/item/templates/ability.mjs
module/data/item/templates/action.mjs
module/data/item/templates/rollable.mjs
module/data/item/templates/targeting.mjs
module/data/item/weapon.mjs
module/data/other/roll-options.mjs
module/dice/ed-roll.mjs
module/documents/actor.mjs
templates/actor/actor-partials/actor-section-top.hbs
templates/item/item-partials/item-details/details/item-details-abilities.hbs
templates/item/item-partials/item-details/details/item-details-talent.hbs
templates/item/item-partials/item-details/partials/targeting.hbs

Make weapon attacks for happy paths (correct weapon type, equip status, etc.) from "attack" type abilities.
This covers:
- ability options:
-Roll Type Details (Important is attack)
-required item status (main, off, tail, unarmed)
-required Combat type (melee, missile, thrown, unarmed)
-reaction typ (pyhsical, mystiacl, social)
- Weapon options:
-Combat type
clicking on an ability with the rollType "attack" set, a check will be done to see if a weapon with the same weaponType is equipped and if the required item status fits the item status of the equipment.
if this is the case, an attack roll is created. Other case are not handled here yet.

Basic attack rolls from abilities

---

module/data/abstract.mjs
module/data/chat/_module.mjs
module/data/chat/attack.mjs
module/data/chat/base-message.mjs
module/data/item/knack-ability.mjs
module/data/item/talent.mjs
module/data/item/templates/ability.mjs
module/data/roll/attack.mjs
module/dice/ed-roll.mjs
module/documents/chat.mjs
template.json

- Add functionality for automatically attaching click listeners to ChatMessage HTMLs.
- Add Attack ChatMessage data model
- Add empty click handlers for attack message buttons
Functionality for chat message buttons follows in another story.

Create attack ChatMessage document and data model

---

module/data/chat/attack.mjs
module/data/item/templates/ability.mjs
module/data/item/weapon.mjs
module/data/roll/ability.mjs
module/data/roll/common.mjs
module/data/roll/damage.mjs
module/dice/ed-roll.mjs
templates/chat/chat-flavor/damage-roll-flavor.hbs

- add roll type "damage"
- add damage roll options
- roll damage from attack message
Currently damage rolls are only created automatically from weapon items.
Functionality for applying damage from a damage message comes in another story.

Add damage roll and options

---

lang/de.json
module/config.mjs
module/data/chat/_module.mjs
module/data/chat/attack.mjs
module/data/chat/base-message.mjs
module/data/chat/damage.mjs
module/data/item/weapon.mjs
module/data/roll/damage.mjs
module/documents/actor.mjs
template.json
templates/chat/chat-flavor/damage-roll-flavor.hbs
templates/item/item-partials/item-details/details/item-details-weapon.hbs

- "apply damage" applies damage to all currently targeted tokens' actors
- "take damage" is only visible if the user has an assigned character, to which the damage will be applied
- each application of damage creates a transaction of the damage in the message itself
- each transaction can be undone, this deductes the damage dealt from the recorded actors current damage

Add functionality to damage message buttons

---

module/applications/actor/base-sheet.mjs
module/data/item/templates/ability.mjs
module/data/roll/attack.mjs
module/documents/actor.mjs
templates/actor/actor-tabs/general.hbs
templates/chat/chat-flavor/attack-roll-flavor.hbs

MVP approach for attacking without an ability:
- add 3 buttons to attack from the general tab in the character sheet: weapon, unarmed, tail
- all attack types use DEX attribute as base roll step
- for now: difficulty is always the max physical defense of all selected targets
- add functions in the actor document
- "weapon attack": take the first currently equipped weapon or draw one if none equipped and attack with it, damage as usual
- "unarmed attack": make unarmed attack, damage as usual
- "tail attack": if no weapon attached (`itemStatus === "tail"`) make an unarmed attack, otherwise an attack of type "melee". even though the attack test is unarmed, it still uses a weapon and must be handled accordingly,
- -2 penalty of tail attack follows when active effects are available

Add buttons to attack without an ability

---

lang/de.json
module/applications/global/prompt-factory.mjs
module/config.mjs
module/data/item/templates/ability.mjs
module/data/item/weapon.mjs
module/documents/actor.mjs
templates/item/item-partials/item-details/details/item-details-weapon.hbs

- add new data field for weapons indicating the type of item status that's the default for wielding it
_add function for drawing a weapon_
- list all weapons available
- select by click
- set itemstatus to wieldingtype of weapon
_add function for switching a weapon_
- if equipped weapon provided: set itemStatus to "carried"
- if not provided: set all weapons' itemStatus to "carried"
- then draw weapon as above
_attacking checks for correct weapon_
- if correct weapon type but wrong status -> switch weapon
- if no weapon equipped at all -> draw weapon

Draw and switch weapon on attack

---

module/data/chat/base-message.mjs
module/data/chat/damage.mjs
module/dice/ed-roll.mjs
module/documents/chat.mjs
module/hooks/chat.mjs
templates/chat/tooltip.hbs

Fix some V13 related bugs:
- hook "renderChatMessage" is renamed and uses HTMLElement instead of query
- Chat's `getHTML` is now `renderHTML` and uses HTMLElement instead of jQuery
- fix dice tooltip template to make it expandable again

ed-roll-fix-v13-changes

---

lang/de.json
module/applications/_module.mjs
module/data/abstract.mjs
module/data/actor/pc.mjs
module/data/actor/templates/common.mjs
module/data/actor/templates/description.mjs
module/data/actor/templates/movement.mjs
module/data/actor/templates/namegiver.mjs
module/data/actor/templates/sentient.mjs

The automatically generated keys for Earthdawn Active Effects changes were not correctly filtered based on  `_EAE_EXCLUDE_KEYS`. Fixed.
Add localization for actor data fields that are present in the keys list, for a better idea of the looks.

Fix EAE change key filtering and add localization

---

lang/de.json
lang/en.json
module/applications/configs/base-config-sheet.mjs
module/applications/configs/constraints-config.mjs
module/applications/item/item-sheet.mjs
module/config.mjs
module/data/common/_module.mjs
module/data/common/restrict-require.mjs
module/data/item/_module.mjs
module/data/item/devotion.mjs
module/data/item/skill.mjs
module/data/item/talent.mjs
module/data/item/templates/ability.mjs
module/data/item/templates/increasable-ability.mjs
module/data/item/templates/knack-item.mjs
module/utils.mjs
templates/configs/constraints-config.hbs
templates/configs/spell-enhancements-config.hbs
templates/form/input/base-constraint.hbs
templates/form/input/configurable-array-summary.hbs
templates/item/item-partials/item-details/descriptions/item-description-knackAbility.hbs
templates/item/item-partials/item-details/descriptions/item-description-knackKarma.hbs
templates/item/item-partials/item-details/descriptions/item-description-knackManeuver.hbs
templates/item/item-partials/item-details/details/item-details-spell.hbs
templates/item/item-partials/item-details/partials/abilities.hbs

Add requirements and restrictions as config apps (like spell enhancements).
Move reference to other unspecific Items from UUIDFields to EdId-Fields, such that they're more easily searched for in a world or embedded.

chris-rework-knack-data-model-approach

---

module/applications/effect/eae-sheet.mjs
module/data/effects/eae.mjs

Effects on Items can either be applied to the parent item itself, to a targeted item, or to the actor the item belongs to.
Make the choices mutually exclusives to achieve that.

active-effects-mutually-exclusive-application-targets

---

lang/de.json
module/applications/effect/eae-sheet.mjs
module/config/_module.mjs
module/config/effects.mjs
module/config/system.mjs
module/data/effects/eae.mjs
templates/effect/details.hbs
templates/effect/execution.hbs

Add a field to run custom javascript from active effects.
Add selection of execution time. This is not functional yet and will be implemented when Combat is worked on.
Until then, a "Run" button is added for convenience.

add-basis-for-executing-active-effects

---

module/documents/actor.mjs

resolves #972 
strain never causes a wound and therefore never causes knockdown
in addition, a wound from standard damage is created if the damage is **equal** or higher

fix wound calculation for strain

---

module/applications/actor/character-sheet.mjs
module/applications/actor/creature-sheet.mjs
module/applications/actor/dragon-sheet.mjs
module/applications/actor/group-sheet.mjs
module/applications/actor/horror-sheet.mjs
module/applications/actor/loot-sheet.mjs
module/applications/actor/npc-sheet.mjs
module/applications/actor/spirit-sheet.mjs
module/applications/actor/trap-sheet.mjs
module/applications/actor/vehicle-sheet.mjs
module/applications/advancement/assign-legend.mjs
module/applications/global/prompt-factory.mjs
module/applications/global/roll-prompt.mjs
module/applications/item/class-item-sheet.mjs
module/applications/item/item-sheet.mjs
module/applications/journal/journal-sheet.mjs
module/data/actor/pc.mjs
module/dice/ed-roll.mjs
module/hooks/init.mjs
module/tours/ed-tours.mjs
module/utils.mjs

Adjust imports to new Foundry's new ESM structures to eliminate deprecation warnings.

solve-warnings-in-foundry-core-13.338

---

module/documents/combat.mjs

Execute executable ActiveEffects (:P) on automatically during combat events (combat, round, turn -> start/end)

active-effect-add-execution-in-combat-cycle

---

lang/en.json

Last of the obvious changes to actor and item sheets as well as roll dialogues to help with formatting with the .less.
The follow inputs have been made to the en.json:
ED.Sheet.Tabs.x
ED.Dialogs.Tabs.x
ED.Dialogs.RollPrompt.x
ED.Dialogs.Buttons.roll
ED.Data.Item.Labels.PhysicalItems.Weight.value
The following formatting changes have been made to the en.json:
ED.Dialogs.Buttons moved to alphabetical order

en.json updates

---

module/applications/_module.mjs
module/applications/actor/character-generation-prompt.mjs
module/applications/actor/common-sheet.mjs
module/applications/advancement/assign-legend.mjs
module/applications/advancement/class-advancement.mjs
module/applications/advancement/learn-spell.mjs
module/applications/advancement/lp-history.mjs
module/applications/api/_module.mjs
module/applications/api/application.mjs
module/applications/api/applicationEd.mjs
module/applications/api/dialog.mjs
module/applications/api/document-sheet-mixin.mjs
module/applications/combat/start-round-combatant-prompt.mjs
module/applications/configs/base-config-sheet.mjs
module/applications/global/document-creation.mjs
module/applications/global/prompt-factory.mjs
module/applications/global/roll-prompt.mjs
module/applications/item/item-sheet.mjs
module/data/actor/pc.mjs
module/data/item/devotion.mjs
module/data/item/path.mjs
module/data/item/questor.mjs
system.json
templates/actor/cards/ability-card.hbs
templates/global/card-options-chat.hbs
templates/global/card-options-class-upgrade.hbs
templates/global/card-options-effect.hbs
templates/global/card-options-enhance.hbs
templates/item/item-partials/item-section-top.hbs

Closes #1636
Create common super classes and mixins for common `Application`s.
For adjustments concerning all types of a Application edit the `DEFAULT_OPTIONS` of:
- `ApplicationEd` for generic apps like the roll prompt, or lp history
- `DocumentSheetEd` for Item and Actor sheets (can be extended to other documents like Journals, etc.)
- `DialogEd` for dialogs like increase prompts, and those from the prompt factory
All applications should now have the common css class `"ed4e"`

1636-refactoring-sheet-global-class

---

module/applications/item/item-sheet.mjs

due to some changes, the scrollable class was missing on item tabs

add scrollable class to all item tabs

---

.lintstagedrc.yaml
package.json
utils/consolidate-lang-json.mjs
utils/format-lang-json.mjs
utils/lint-json.mjs

The pre-commit hook now fails if es-lint finds non-fixable issues.
JSON lang linting has been extended. When a lang file has been changed, all lang files are consolidated. This means, that all lang files are updated to have all the same keys across all files. If a key is inserted the get a default "TODO: Add translation" value.
This needs to be done once, to bring all lang files up to the same state, and from then on, changes in PRs in only one lang file are reflected in other files as well.

Add localization JSON consolidation and linting utilities

---

module/data/abstract.mjs
module/data/common/matrix.mjs
module/settings.mjs
module/utils.mjs
templates/item/item-partials/item-details/details/item-details-abilities.hbs
templates/item/item-partials/item-details/details/item-details-physicalItems.hbs
templates/item/item-partials/item-details/partials/matrix.hbs

Add matrix fields to "physical item" and "talent" sheets.
To add a matrix to an item, set the edid of that item to "matrix" (or as defined in the settings).
Then the basic matrix data fields appear.
Making it nice comes later.

items-with-matrix-property-sheets

---

module/applications/actor/character-generation-prompt.mjs
module/applications/advancement/class-advancement.mjs
module/data/actor/templates/namegiver.mjs
module/data/item/talent.mjs
module/data/item/templates/ability.mjs
module/data/item/templates/class.mjs
module/data/other/character-generation.mjs
module/packs/tour-items/talent_Artefaktgeschichte_dhini7gGvVSPwLY3.json
module/packs/tour-items/talent_Beeindrucken_Hz3qxCcQtl8Ze4Nq.json
module/packs/tour-items/talent_Erster_Eindruck_aRLtHFmr1hfrpS4K.json
module/packs/tour-items/talent_Fadenweben_h5hNZuAPIVlaVxBD.json
module/packs/tour-items/talent_Feilschen_ARB2Ld2ZLlLGEgSX.json
module/packs/tour-items/talent_Fremdsprachen_QdaMwao77qyLldxy.json
module/packs/tour-items/talent_Gef_hlsmelodie_cfApFKn4MeOBuIss.json
module/packs/tour-items/talent_Gewinnendes_L_cheln_7SODC2KaKrE1PGiW.json
module/packs/tour-items/talent_Herzliches_Lachen_giGnZQPW2Oy9Wa1l.json
module/packs/tour-items/talent_Hieb_Ausweichen_Z2IhYwBjKfGTld6Q.json
module/packs/tour-items/talent_Konversation_XHzKVTNuVbC1UDfm.json
module/packs/tour-items/talent_Lesen_Schreiben_HLXG6scpImEg35b1.json
module/packs/tour-items/talent_Nahkampfwaffen_nXGNz0vAznkNPf9I.json
module/packs/tour-items/talent_Unterhalten_h9wUXkZ9LTsd6EP4.json
module/packs/tour-items/talent_Verspotten_10wJAcvY00T5yU7y.json
module/packs/tour-items/talent_Wurfwaffen_RSu48Yl3Hq8umJyA.json
templates/item/item-partials/item-details/details/item-details-talent.hbs

Since "thread weaving" and "spellcasting" roll types are now part of abilities, the information in the magic field can be moved there. The castingType is a roll type detail for "thread weaving". Naming is getting confusing, but that's just the nature of spellcasting (which is one talent) vs. thread weaving (multiple talents), but only casting disciplines are different.
This also includes getting a potential casting type from a class item. May be relevant to PR #1519

Move ability magic details into roll type

---

module/applications/_module.mjs
module/applications/actor/common-sheet.mjs
module/applications/actor/sentient-sheet.mjs
module/applications/api/application.mjs
module/applications/workflow/_module.mjs
module/applications/workflow/attune-matrix-prompt.mjs
module/config/system.mjs
module/data/item/templates/matrix.mjs
module/documents/actor.mjs
module/workflows/attune-matrix-workflow.mjs
module/workflows/workflow/actor-workflow.mjs
module/workflows/workflow/item-workflow.mjs
templates/actor/actor-tabs/spells.hbs
templates/workflow/attune-matrix.hbs

Add basic UI for attuning spell matrices.
- add listing matrices in actor's "spells" tab
- add button to attune all
- click matrix in "spells" tab to focus in clicked matrix
- add temporary inline styling
NOT ADDRESSED (create new issues for that?)
- spells that can share a matrix that is not of type "shared" (e.g., resist element versions, otter swim/gills)
- attune on the fly
(otherwise this PR got too big)

attuning-spell-matrix

---

utils/consolidate-lang-json.mjs
utils/lint-json.mjs

This pull request improves the handling of language file consolidation by:
- Refactoring `consolidateLangJson` to use a lead language file parameter.
- Streamlining processing logic to rely on the lead file for key handling.
- Enhancing `lint-json` validation logic for lead file and ISO 639-1 compliance.
- Improving code maintainability with clear comments and unused variable removal.
This version of the lang linting requires a particular process of working with localization files. Only one localization file can be committed at a time, which will be taken as the lead file. On the basis of the lead file, all other language files are updated, deleting keys not in the lead file and adding those missing in other files.
This means that possible discrepancies between files at the moment need to …

Refactor language JSON consolidation logic

---

module/applications/item/physical-item-sheet.mjs

The pull request includes the following changes:
- Added the missing `TextEditor` import in `physical-item-sheet`.
- Updated the code to conform to ES module usage, as global assignment is deprecated in Foundry V13.

Add missing import to physical-item-sheet

---

lang/de.json
lang/en.json
lang/fr.json
lang/pl.json
module/applications/item/physical-item-sheet.mjs
module/config/system.mjs
module/data/item/_module.mjs
module/data/item/templates/grimoire.mjs
module/data/item/templates/matrix.mjs
module/data/item/templates/physical-item.mjs
module/utils.mjs
templates/chat/chat-flavor/damage-roll-flavor.hbs
templates/item/item-partials/item-details/details/item-details-physicalItems.hbs
templates/item/item-partials/item-details/partials/grimoire.hbs

This PR introduces the GrimoireTemplate class to the item data model, enabling support for grimoire items in the system.
- Schema definition for grimoire items with spell collection and owner reference
- Properties to check grimoire status and ownership
- Lifecycle methods to handle grimoire data initialization and cleanup on item creation/update
- Method to add spells to a grimoire with appropriate validation and user notifications
This update lays the groundwork for managing spell collections within grimoire items and ensures data integrity when items change type.
No breaking changes to existing item templates.

Add Grimoire Item Template

---

lang/de.json
lang/en.json
lang/fr.json
lang/pl.json
module/applications/api/dialog.mjs
module/applications/workflow/_module.mjs
module/applications/workflow/select-extra-threads-prompt.mjs
module/config/magic.mjs
module/config/rolls.mjs
module/data/common/metrics.mjs
module/data/item/spell.mjs
module/data/item/templates/ability.mjs
module/data/item/templates/matrix.mjs
module/data/roll/_module.mjs
module/data/roll/weaving.mjs
module/documents/actor.mjs
module/utils.mjs
module/workflows/workflow/attune-workflow.mjs
templates/chat/chat-buttons/cast-spell.hbs
templates/chat/chat-flavor/thread-weaving-roll-flavor.hbs
templates/workflow/select-extra-threads.hbs

This pull request introduces the foundational logic for spell threadweaving, including methods for weaving, resetting, and stopping threads on spells. The SpellData model is extended with additional schema fields, computed properties, and workflow methods to support threadweaving mechanics, spell learning, and related game logic.
This update also improves validation, localization, and integration with prompts and roll workflows.
A simple test would be to create a character, with a detailed spell (including extra threads choices) and a corresponding thread weaving talent (and an optional matrix, only relevant for matrix held threads).
Then call from the console:
`await spell.system.weaveThreads( threadWeavingItem, matrixItemIfAny)`

Implement Spell Threadweaving Basics and Data Model Enhancements

---

lang/de.json
lang/en.json
lang/fr.json
lang/pl.json
module/config/rolls.mjs
module/data/item/talent.mjs
module/data/item/templates/grimoire.mjs
module/data/item/templates/matrix.mjs
module/data/roll/attuning.mjs
module/data/roll/common.mjs
module/documents/actor.mjs
module/workflows/workflow/_module.mjs
module/workflows/workflow/actor-workflow.mjs
module/workflows/workflow/attune-grimoire-workflow.mjs
module/workflows/workflow/attune-matrix-workflow.mjs
module/workflows/workflow/rollable.mjs
templates/item/item-partials/item-details/partials/grimoire.hbs

This pull request introduces grimoire attunement workflows, as well as improvements to roll options and their initialization. The key changes include the addition of a new `AttuneGrimoireWorkflow`, updates to the `GrimoireTemplate` class to support attuned spells, modifications to roll options for better flexibility, and refactoring of existing workflows to align with the new structure.
* **New `AttuneGrimoireWorkflow` Class**: Introduced a dedicated workflow for attuning grimoires. This includes steps for selecting a grimoire, selecting a spell, and processing the attunement roll. It also integrates with the `AttuningRollOptions` class for roll handling. (`module/workflows/workflow/attune-grimoire-workflow.mjs`, [module/workflows/workflow/attune-grimoire-workflow.mjsR1-R169](diffhunk://#d …

Attune Grimoire Workflow

---

lang/de.json
lang/en.json
lang/fr.json
lang/pl.json
module/applications/api/dialog.mjs
module/config/_module.mjs
module/data/item/spell.mjs
module/data/item/templates/matrix.mjs
module/data/roll/_module.mjs
module/data/roll/attuning.mjs
module/data/roll/common.mjs
module/data/roll/spellcasting.mjs
module/data/roll/weaving.mjs
module/documents/actor.mjs
module/utils.mjs
module/workflows/workflow/_module.mjs
module/workflows/workflow/base-casting-workflow.mjs
module/workflows/workflow/grimoire-casting-workflow.mjs
module/workflows/workflow/matrix-casting-workflow.mjs
module/workflows/workflow/raw-casting-workflow.mjs
module/workflows/workflow/spellcasting-workflow.mjs
module/workflows/workflow/workflow.mjs
templates/chat/chat-flavor/spellcasting-roll-flavor.hbs
templates/item/item-partials/item-details/partials/matrix.hbs
templates/workflow/select-extra-threads.hbs

This pull request introduces the foundation for using spellcasting as workflows. It comes with a workflow for matrix casting. Grimoire and raw are still to come. 
⚠️  This is only functional, not usable from the UI yet! ⚠️ 
The changes include improvements to dialog handling, spellcasting logic, and matrix template validation. Below is a summary of the most significant changes:
* Adjusted various German localization strings for consistency and clarity, including replacing single quotes with double quotes in specific contexts. [[1]](diffhunk://#diff-b856eeca8165aed4012d1d98ca6e927f20366c9c1272932ad9d8004358c1f38dL332-R332) [[2]](diffhunk://#diff-b856eeca8165aed4012d1d98ca6e927f20366c9c1272932ad9d8004358c1f38dR341-R344)
* Added new localization keys for spellcasting features, such as …

Add (matrix) spellcasting workflow foundation

---

module/config/_module.mjs
system.json

It works without the function. CSS hot reload is still not possible because of https://github.com/foundryvtt/foundryvtt/issues/9958

Remove hot reload functionality for Handlebars templates

---

lang/de.json
lang/en.json
lang/fr.json
lang/pl.json
module/applications/_module.mjs
module/applications/scene/_module.mjs
module/applications/scene/scene-config.mjs
module/config/magic.mjs
module/config/system.mjs
module/hooks/init.mjs
templates/configs/scene-config-tab-ed.hbs

This pull request introduces a new feature for managing astral pollution in scenes. The updates include a custom scene configuration class, and additional configuration options for astral pollution.
* **Localization Updates**  
Added new localization strings for astral pollution categories (`safe`, `open`, `tainted`, `corrupt`) and scene configuration labels and hints in `lang/de.json`. [[1]](diffhunk://#diff-b856eeca8165aed4012d1d98ca6e927f20366c9c1272932ad9d8004358c1f38dR393-R398) [[2]](diffhunk://#diff-b856eeca8165aed4012d1d98ca6e927f20366c9c1272932ad9d8004358c1f38dR3210-R3215)
* **Astral Pollution Configuration**  
Defined the `astralSpacePollution` object in `module/config/magic.mjs`, which includes labels and modifiers for different pollution levels.
* **Custom Scene Configuration …

Add scene configuration and astral pollution options for Earthdawn

---

earthdawn4e.css
less/earthdawn4e.less
less/global/forms.less
templates/item/item-partials/item-details.hbs

Add a bit of a margin to `<fieldset>`s for improved spacing, better legibility, ...
(also layout ED-ID inputs in Item IDs the same)

Add fieldset margin

---

module/data/item/power.mjs
module/data/item/templates/ability.mjs
module/data/item/templates/rollable.mjs
module/data/item/weapon.mjs
module/documents/actor.mjs

resolves #1792 
resolves #1793 
since the rollFunc is not called for specific roll operations, I set most of the to "rollAbility" for the moment. now every ability is rerouted to roll ability no matter the rollType if it is rolled directly, without the use of an specific workflow (like attack)

fix not working rolls

---

module/hooks/ready.mjs
module/services/migrations/type-transformation-manager.mjs
module/services/migrations/v082/type-transformations.mjs

this is fixing the deep db migration of actor and item types. it is a call triggered after migrations are already done and triggered by the ready hook. It will only consider items and actors which where added to an array for later fixing, so this will only run if there are items or actor to be fixed
this is the base for all further migration issues

Pc migration small

---

module/config/_module.mjs
module/data/roll/ability.mjs
module/data/roll/attack.mjs
module/data/roll/attuning.mjs
module/data/roll/common.mjs
module/data/roll/horror-mark.mjs
module/data/roll/initiative.mjs
module/data/roll/recovery.mjs
module/data/roll/spellcasting.mjs
module/data/roll/warping.mjs
module/data/roll/weaving.mjs

Roll options can be optionally initialized automatically by having subclasses implement the appropriate initialization methods. This was done automatically on creation, so it could not be avoided and wasn't documented at all.
This PR factors this automatic initialization out of standard construction and moves it to a dedicated factory method `fromData`. This then allows for better documentation of the init data that does not get persisted in the roll options.
Damage Roll Options will be done in another PR with #1623.

📝 ♻️ Refactor auto initialization of roll options

---

lang/de.json
lang/en.json
lang/fr.json
lang/pl.json
module/applications/effect/eae-sheet.mjs
module/config/rolls.mjs
module/data/chat/base-message.mjs
module/data/chat/damage.mjs
module/data/roll/ability.mjs
module/data/roll/spellcasting.mjs
module/documents/actor.mjs
module/documents/item.mjs
templates/chat/chat-buttons/assign-effect.hbs
templates/chat/chat-flavor/ability-roll-flavor.hbs
templates/chat/chat-flavor/attack-roll-flavor.hbs
templates/chat/chat-flavor/effect-roll-flavor.hbs
templates/chat/chat-flavor/spellcasting-roll-flavor.hbs

Resolves #284
Currently implemented for Ability and Spell rolls.
Additional rolls can easily be added by passing an `itemForEffects` to the rendering context and add the button partial to the chat message template.

Apply transferable effects to target from chat 

---

lang/de.json
lang/en.json
lang/fr.json
lang/pl.json
module/applications/item/item-sheet.mjs
module/data/abstract/system-data-model.mjs
module/data/common/_module.mjs
module/data/common/restrict-require.mjs
module/data/item/knack-ability.mjs
module/data/item/spell-knacks.mjs
module/data/item/talent.mjs
module/data/item/templates/knack-item.mjs
module/services/migrations/v082/field-migrations/knack-source.mjs
module/utils.mjs
templates/actor/actor-tabs/talents.hbs
templates/item/item-partials/item-details/descriptions/item-description-knackAbility.hbs
templates/item/item-partials/item-details/descriptions/item-description-knackKarma.hbs
templates/item/item-partials/item-details/descriptions/item-description-knackManeuver.hbs

Closes #446 .
Opting for a simple approach here: spell knacks inherit from SpellData and mixin the KnackTemplate.
Whenever the knack is created or updated with the source spell edid, its system data is pulled and copied into the knack. This way, spell knacks are just normal spells with changed data, that belong to another spell.

🗃️ Add Spell Knack Data Model

---

earthdawn4e.css
less/global/global.less
less/global/icons.less
less/sheets/actor-sheet-layout.less
templates/actor/actor-partials/actor-section-top-pc.hbs
templates/actor/actor-tabs/classes.hbs
templates/actor/actor-tabs/configuration.hbs
templates/actor/actor-tabs/description.hbs
templates/actor/actor-tabs/devotions.hbs
templates/actor/actor-tabs/equipment.hbs
templates/actor/actor-tabs/general.hbs
templates/actor/actor-tabs/legend.hbs
templates/actor/actor-tabs/notes.hbs
templates/actor/actor-tabs/powers.hbs
templates/actor/actor-tabs/reputation.hbs
templates/actor/actor-tabs/skills.hbs
templates/actor/actor-tabs/specials.hbs
templates/actor/actor-tabs/spells.hbs
templates/actor/actor-tabs/talents.hbs
templates/actor/cards/ability-card.hbs
templates/actor/cards/health-character-card.hbs
templates/global/card-options-class-upgrade.hbs
templates/global/card-options-enhance.hbs

Formatting complete on languages, but needs work with .js to finish. Including an upgrade up arrow in the sub headers to add more after chargen (this only appears in edit mode)... this needs coding in .js.
All upgrades are not restricted to edit mode only and all sections are updated to contain the right class to do this in future.
all + - buffers are now on game mode only.
uuid icons are all formatted to appear like all other buttons (including hover over which was not working prior)

language-container
